// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package custSql

import (
	"database/sql"
)

type Item struct {
	Accountid          sql.NullInt64
	Itemid             int64
	Defindex           sql.NullInt64
	Paintindex         sql.NullInt64
	Rarity             sql.NullInt64
	Quality            sql.NullInt64
	Paintwear          sql.NullInt64
	Paintseed          sql.NullInt64
	Killeaterscoretype sql.NullInt64
	Killeatervalue     sql.NullInt64
	Customname         sql.NullString
	Inventory          sql.NullInt64
	Origin             sql.NullInt64
	Questid            sql.NullInt64
	Dropreason         sql.NullInt64
	Musicindex         sql.NullInt64
	Entindex           sql.NullInt64
	Petindex           sql.NullInt64
	Paramd             sql.NullInt64
	Paramm             sql.NullInt64
	Params             sql.NullInt64
	Floatvalue         sql.NullFloat64
	Maxfloat           sql.NullFloat64
	Minfloat           sql.NullFloat64
	Weapontype         sql.NullString
	Itemname           sql.NullString
	Rarityname         sql.NullString
	Qualityname        sql.NullString
	Originname         sql.NullString
	Wearname           sql.NullString
	Markethashname     sql.NullString
	Lastupdated        sql.NullInt64
}

type Modifier struct {
	Itemid         int64
	Modifierid     sql.NullInt64
	Modifiertype   string
	Slot           sql.NullInt64
	Wear           sql.NullFloat64
	Scale          sql.NullFloat64
	Rotation       sql.NullFloat64
	Tintid         sql.NullInt64
	Offsetx        sql.NullFloat64
	Offsety        sql.NullFloat64
	Offsetz        sql.NullFloat64
	Pattern        sql.NullInt64
	Markethashname sql.NullString
}
