// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Item struct {
	M                  string
	D                  string
	S                  string
	Accountid          sql.NullInt64
	Itemid             string
	Defindex           sql.NullInt64
	Paintindex         sql.NullInt64
	Rarity             sql.NullInt64
	Quality            sql.NullInt64
	Paintwear          sql.NullInt64
	Paintseed          sql.NullInt64
	Killeaterscoretype sql.NullInt64
	Killeatervalue     sql.NullInt64
	Customname         sql.NullString
	Inventory          sql.NullInt64
	Origin             sql.NullInt64
	Questid            sql.NullInt64
	Dropreason         sql.NullInt64
	Musicindex         sql.NullInt64
	Entindex           sql.NullInt64
	Petindex           sql.NullInt64
}

type Mod struct {
	Modid         int64
	Slot          sql.NullInt64
	Stickerid     sql.NullInt64
	Wear          sql.NullFloat64
	Scale         sql.NullFloat64
	Rotation      sql.NullFloat64
	Tintid        sql.NullInt64
	Offsetx       sql.NullFloat64
	Offsety       sql.NullFloat64
	Offsetz       sql.NullFloat64
	Pattern       sql.NullInt64
	Highlightreel sql.NullInt64
}

type Modschain struct {
	Modid  int64
	M      string
	D      string
	S      string
	Itemid string
}

type Modssticker struct {
	Modid  int64
	M      string
	D      string
	S      string
	Itemid string
}
