CREATE TABLE items(
	AccountID          INTEGER,
	ItemID             INTEGER PRIMARY KEY,
	DefIndex           INTEGER,
	PaintIndex         INTEGER,
	Rarity             INTEGER,
	Quality            INTEGER,
	Paintwear          INTEGER,
	Paintseed          INTEGER,
	Killeaterscoretype INTEGER,
	Killeatervalue     INTEGER,
	Customname         TEXT,
	Inventory          INTEGER,
	Origin             INTEGER,
	Questid            INTEGER,
	Dropreason         INTEGER,
	Musicindex         INTEGER,
	Entindex           INTEGER,
	Petindex           INTEGER,
	ParamD             INTEGER,
	ParamM             INTEGER,
	ParamS             INTEGER,
	FloatValue         REAL,
	MaxFloat           REAL,
	MinFloat           REAL,
	WeaponType         TEXT,
	ItemName           TEXT,
	RarityName         TEXT,
	QualityName        TEXT,
	OriginName         TEXT,
	WearName           TEXT,
	MarketHashName     TEXT,
	LastUpdated        INTEGER
);

CREATE TABLE Modifiers(
	ItemID          INTEGER PRIMARY KEY,
	ModifierID      INTEGER,
	ModifierType    TEXT CHECK(ModifierType IN ('sticker', 'chain')) NOT NULL,
	Slot            INTEGER,
	Wear            REAL,
	Scale           REAL,
	Rotation        REAL,
	TintId          INTEGER,
	OffsetX         REAL,
	OffsetY         REAL,
	OffsetZ         REAL,
	Pattern         INTEGER,
	MarketHashName  TEXT
);
