erDiagram
  ip["Item Protobuf"] {
    int AccountID
    int ItemID PK
    int DefIndex
    int PaintIndex
    int Rarity
    int Quality
    int Paintwear
    int Paintseed
    int Killeaterscoretype
    int Killeatervalue
    text Customname
    int Inventory
    int Origin
    int Questid
    int Dropreason
    int Musicindex
    int Entindex
    int Petindex
    int ParamD
    int ParamM
    int ParamS
    time lastUpdated
    float FloatValue
    float MaxFloat
    float MinFloat
    text WeaponType
    text ItemName
    text RarityName
    text QualityName
    text OriginName
    text WearName
    text MarketHashName
  }

  mp["Modifier Protobuf"] {
    int ItemID PK, FK
    int ModifierID
    int Slot
    float Wear
    float Scale
    float Rotation
    int TintId
    float OffsetX
    float OffsetY
    float OffsetZ
    int Pattern
    text MarketHashName
  }


  ip ||--o{mp : has
